### ISSUE TITLE
Crashes server with errors when using /sponge plugins reload

### ISSUE THREAD

**Issue by WinggedPhantom** [poqdavid/VirtualTool#5]
Server just spits out errors pointing to Virtual Tool when reloading.
https://pastebin.com/cU3yuYRY

**Comment by poqdavid** [comment]
I will look in to it don't worry but it might take a bit of time

**Comment by SnowBlitzz** [comment]
Yes I am experiencing that too when I do /sponge plugins reload

**Comment by poqdavid** [comment]
Same log?

**Comment by SnowBlitzz** [comment]
Yeah

**Comment by poqdavid** [comment]
Yah well I will fix it and I am also waiting for sponge to fix a bug so please be patient

**Comment by vectrixdevelops** [comment]
Boi

**Comment by codeHusky** [comment]
#8

**Comment by ryantheleach** [comment]
"waiting for sponge"

This just crashed a server made by Inscrutable, what bug are you waiting on?

Also looking at the error, rather then calling the same thing that caused the error, you should probably instead print the error.

**Comment by Jaskirat-Boparai** [comment]
I am also experiencing this issue: https://pastebin.com/YDjXUHWb

version: VirtualTool-1.10.2-2.6.jar
sponge version: spongeforge-1.10.2-2281-5.2.0-BETA-2401.jar

**Comment by poqdavid** [comment]
@Jaskirat-Boparai there is a problem with the path for settings

**Comment by dualspiral** [comment]
@poqdavid I don't understand why you don't just pull #8 (even as a stopgap) or fix this in a cleaner way. This is really quite a serious bug when you think about it, if you can't save the config, you try to save the config. It looks like you're trying to reload it - but if saving has caused an exception before it's more than likely going to cause an exception again.

The issue in sponge I believe you're waiting on is https://github.com/SpongePowered/SpongeCommon/issues/1323. I want that fixed too, and might just look into it when I get the chance. However, that's all well and good, but it's nothing to do with this actual error, in which you just cause a stack overflow because you try to save it until it crashes - and that's irresponsible. 

Do as @ryantheleach suggests, if it fails to save, tell the user and stop trying to save. Don't just send their server into a death spiral.

**Comment by poqdavid** [comment]
I will fix the reload problem I just need few more days to finish a other plugin I am working on

**Comment by Jaskirat-Boparai** [comment]
Awaiting a fix keenly.

**Comment by Brend-Smits** [comment]
..

**Comment by poqdavid** [comment]
Guys I understand this is a long delay for such a small fix and thanks for waiting and I am pretty sure I can fix it like in a week or something so no worries

**Comment by EmanYm** [comment]
Eleven days ago you said `a few more days`
three days ago you said `a week or something`

One of my admins did `/sponge plugins reload` while I wasn't there...five minutes later I get a text saying the server is slow.  I come back to my computer with a **1.2GB log file** and VirtualTool having a meltdown.

Why can't you apply the fix now, and then later you can finish whatever else you're working on.
Something that creates a 1GB log file in under five minutes is a SERIOUS issue.

Seriously, though.  There is already a pull request that says it will fix it.  Even a "bubblegum and bail twine" fix will be better than nothing right now.  approve the pull, and come back to it later.

It's been more than two months since the first post.
More than two weeks since the pull request.
It's not that difficult to click a button.  In the meantime you're loosing users for something that should not be an issue.

**Comment by Brend-Smits** [comment]
EmanYm, while the author waits another few days, I've merged the PR on my fork and provided a download in the release section. The PR is a dirty fix and will error when reloading, but it won't crash

**Comment by poqdavid** [comment]
Well i just made a fix and pushed it as far i tested the changes it works fine
